site_name: CrowdWire Documentation
site_url: http://atnog-crowdwire1.av.it.pt/
repo_url: https://github.com/Crowd-Wire/ProjectDocumentation
repo_name: CrowdWire Documentation

theme:
   name: material
   favicon: assets/favicon.ico
   logo: assets/logo.png
   palette:
      primary: light blue
      accent: light blue
   features:
    - navigation.instant
    - navigation.top

plugins:
  - render_swagger

extra:
   social:
    - icon: fontawesome/brands/github
      link: https://github.com/Crowd-Wire
      name: CrowdWire Repository